require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users/link_managements", type: :request do
  # Users::LinkManagement. As you add validations to Users::LinkManagement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Users::LinkManagement.create! valid_attributes
      get users_link_managements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      link_management = Users::LinkManagement.create! valid_attributes
      get users_link_management_url(users_link_management)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_users_link_management_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      link_management = Users::LinkManagement.create! valid_attributes
      get edit_users_link_management_url(users_link_management)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Users::LinkManagement" do
        expect do
          post users_link_managements_url, params: { users_link_management: valid_attributes }
        end.to change(Users::LinkManagement, :count).by(1)
      end

      it "redirects to the created users_link_management" do
        post users_link_managements_url, params: { users_link_management: valid_attributes }
        expect(response).to redirect_to(users_link_management_url(@users_link_management))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Users::LinkManagement" do
        expect do
          post users_link_managements_url, params: { users_link_management: invalid_attributes }
        end.to change(Users::LinkManagement, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post users_link_managements_url, params: { users_link_management: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested users_link_management" do
        link_management = Users::LinkManagement.create! valid_attributes
        patch users_link_management_url(users_link_management), params: { users_link_management: new_attributes }
        link_management.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the users_link_management" do
        link_management = Users::LinkManagement.create! valid_attributes
        patch users_link_management_url(users_link_management), params: { users_link_management: new_attributes }
        link_management.reload
        expect(response).to redirect_to(users_link_management_url(link_management))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        link_management = Users::LinkManagement.create! valid_attributes
        patch users_link_management_url(users_link_management), params: { users_link_management: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested users_link_management" do
      link_management = Users::LinkManagement.create! valid_attributes
      expect do
        delete users_link_management_url(users_link_management)
      end.to change(Users::LinkManagement, :count).by(-1)
    end

    it "redirects to the users_link_managements list" do
      link_management = Users::LinkManagement.create! valid_attributes
      delete users_link_management_url(users_link_management)
      expect(response).to redirect_to(users_link_managements_url)
    end
  end
end
